//! Declarative item catalog and archetype registry for NetRust.

use netrust_arena::{ItemLocation, ItemRecord};
use netrust_types::ItemClass;
use serde::{Deserialize, Serialize};

/// Enumeration of canonical item kinds.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ItemKindId {
    // Weapons
    Dagger,
    ShortSword,
    LongSword,
    SilverSaber,
    Mace,
    // Armor
    LeatherArmor,
    ChainMail,
    PlateMail,
    SilverDragonScaleMail,
    CloakOfMagicResistance,
    // Wands
    WandOfStriking,
    WandOfDigging,
    WandOfTeleportation,
    WandOfDeath,
    WandOfWishing,
    WandOfCold,
    WandOfSecretDoorDetection,
    // Potions
    PotionOfHealing,
    PotionOfExtraHealing,
    PotionOfSpeed,
    PotionOfWater,
    // Scrolls
    ScrollOfIdentify,
    ScrollOfTeleportation,
    ScrollOfRemoveCurse,
    ScrollOfEnchantWeapon,
    ScrollOfEnchantArmor,
    ScrollOfCharging,
    // Containers & Tools
    Sack,
    BagOfHolding,
    Chest,
    MagicLamp,
    OilLamp,
    // Rocks & Heavy Objects
    Boulder,
    // Food
    FoodRation,
    Apple,
    Corpse,
    // Spellbooks
    SpellbookOfForceBolt,
    SpellbookOfHealing,
    // Amulets & Quest Artifacts
    AmuletOfYendor,
    AmuletOfReflection,
    // Signature Artifacts
    Excalibur,
    VorpalBlade,
    Mjollnir,
    Magicbane,
    EyeOfTheAethiopica,
    // Quest Artifacts
    OrbOfFate,
    HeartOfAhriman,
    MagicMirrorOfMerlin,
    EyesOfTheOverworld,
    MasterKeyOfThievery,
    TsurugiOfMuramasa,
    PlatinumYendorianExpressCard,
    StaffOfAesculapius,
    OrbOfDetection,
    // Invocation Artifacts & Tools
    BellOfOpening,
    CandelabrumOfInvocation,
    BookOfTheDead,
    WaxCandle,
    // Treasure & Gems
    GoldPieces,
    Luckstone,
}

/// Declarative specification of an item archetype.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ItemArchetype {
    pub id: ItemKindId,
    pub name: &'static str,
    pub class: ItemClass,
    pub weight: u32,
    pub cost: u32,
    pub damage_small: (u32, u32),
    pub damage_large: (u32, u32),
    pub ac_bonus: i32,
    pub is_container: bool,
    pub is_bag_of_holding: bool,
}

pub static ITEM_CATALOG: &[ItemArchetype] = &[
    // Weapons
    ItemArchetype {
        id: ItemKindId::Dagger,
        name: "dagger",
        class: ItemClass::Weapon,
        weight: 10,
        cost: 4,
        damage_small: (1, 4),
        damage_large: (1, 3),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::ShortSword,
        name: "short sword",
        class: ItemClass::Weapon,
        weight: 30,
        cost: 10,
        damage_small: (1, 6),
        damage_large: (1, 8),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::LongSword,
        name: "long sword",
        class: ItemClass::Weapon,
        weight: 40,
        cost: 15,
        damage_small: (1, 8),
        damage_large: (1, 12),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::SilverSaber,
        name: "silver saber",
        class: ItemClass::Weapon,
        weight: 40,
        cost: 75,
        damage_small: (1, 8),
        damage_large: (1, 8),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::Mace,
        name: "mace",
        class: ItemClass::Weapon,
        weight: 30,
        cost: 5,
        damage_small: (1, 6),
        damage_large: (1, 6),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    // Armor
    ItemArchetype {
        id: ItemKindId::LeatherArmor,
        name: "leather armor",
        class: ItemClass::Armor,
        weight: 150,
        cost: 5,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 2,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::ChainMail,
        name: "chain mail",
        class: ItemClass::Armor,
        weight: 300,
        cost: 75,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 5,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::PlateMail,
        name: "plate mail",
        class: ItemClass::Armor,
        weight: 450,
        cost: 600,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 7,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::SilverDragonScaleMail,
        name: "silver dragon scale mail",
        class: ItemClass::Armor,
        weight: 40,
        cost: 1200,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 9,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::CloakOfMagicResistance,
        name: "cloak of magic resistance",
        class: ItemClass::Armor,
        weight: 10,
        cost: 50,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 1,
        is_container: false,
        is_bag_of_holding: false,
    },
    // Wands
    ItemArchetype {
        id: ItemKindId::WandOfStriking,
        name: "wand of striking",
        class: ItemClass::Wand,
        weight: 7,
        cost: 150,
        damage_small: (2, 12),
        damage_large: (2, 12),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::WandOfDigging,
        name: "wand of digging",
        class: ItemClass::Wand,
        weight: 7,
        cost: 150,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::WandOfTeleportation,
        name: "wand of teleportation",
        class: ItemClass::Wand,
        weight: 7,
        cost: 175,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::WandOfDeath,
        name: "wand of death",
        class: ItemClass::Wand,
        weight: 7,
        cost: 500,
        damage_small: (100, 1),
        damage_large: (100, 1),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::WandOfWishing,
        name: "wand of wishing",
        class: ItemClass::Wand,
        weight: 7,
        cost: 500,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::WandOfCold,
        name: "wand of cold",
        class: ItemClass::Wand,
        weight: 7,
        cost: 175,
        damage_small: (6, 6),
        damage_large: (6, 6),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::WandOfSecretDoorDetection,
        name: "wand of secret door detection",
        class: ItemClass::Wand,
        weight: 7,
        cost: 150,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    // Potions
    ItemArchetype {
        id: ItemKindId::PotionOfHealing,
        name: "potion of healing",
        class: ItemClass::Potion,
        weight: 20,
        cost: 100,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::PotionOfExtraHealing,
        name: "potion of extra healing",
        class: ItemClass::Potion,
        weight: 20,
        cost: 150,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::PotionOfSpeed,
        name: "potion of speed",
        class: ItemClass::Potion,
        weight: 20,
        cost: 150,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::PotionOfWater,
        name: "potion of water",
        class: ItemClass::Potion,
        weight: 20,
        cost: 100,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    // Scrolls
    ItemArchetype {
        id: ItemKindId::ScrollOfIdentify,
        name: "scroll of identify",
        class: ItemClass::Scroll,
        weight: 5,
        cost: 20,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::ScrollOfTeleportation,
        name: "scroll of teleportation",
        class: ItemClass::Scroll,
        weight: 5,
        cost: 100,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::ScrollOfRemoveCurse,
        name: "scroll of remove curse",
        class: ItemClass::Scroll,
        weight: 5,
        cost: 80,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::ScrollOfEnchantWeapon,
        name: "scroll of enchant weapon",
        class: ItemClass::Scroll,
        weight: 5,
        cost: 60,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::ScrollOfEnchantArmor,
        name: "scroll of enchant armor",
        class: ItemClass::Scroll,
        weight: 5,
        cost: 80,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::ScrollOfCharging,
        name: "scroll of charging",
        class: ItemClass::Scroll,
        weight: 5,
        cost: 80,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    // Containers
    ItemArchetype {
        id: ItemKindId::Sack,
        name: "sack",
        class: ItemClass::Tool,
        weight: 15,
        cost: 2,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: true,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::BagOfHolding,
        name: "bag of holding",
        class: ItemClass::Tool,
        weight: 15,
        cost: 100,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: true,
        is_bag_of_holding: true,
    },
    ItemArchetype {
        id: ItemKindId::Chest,
        name: "chest",
        class: ItemClass::Tool,
        weight: 600,
        cost: 16,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: true,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::MagicLamp,
        name: "magic lamp",
        class: ItemClass::Tool,
        weight: 20,
        cost: 1000,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::OilLamp,
        name: "oil lamp",
        class: ItemClass::Tool,
        weight: 20,
        cost: 10,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::Boulder,
        name: "boulder",
        class: ItemClass::Rock,
        weight: 6000,
        cost: 0,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    // Food
    ItemArchetype {
        id: ItemKindId::FoodRation,
        name: "food ration",
        class: ItemClass::Food,
        weight: 20,
        cost: 45,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::Apple,
        name: "apple",
        class: ItemClass::Food,
        weight: 2,
        cost: 5,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::Corpse,
        name: "corpse",
        class: ItemClass::Food,
        weight: 50,
        cost: 0,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    // Spellbooks
    ItemArchetype {
        id: ItemKindId::SpellbookOfForceBolt,
        name: "spellbook of force bolt",
        class: ItemClass::Spellbook,
        weight: 50,
        cost: 100,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::SpellbookOfHealing,
        name: "spellbook of healing",
        class: ItemClass::Spellbook,
        weight: 50,
        cost: 100,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    // Amulets & Quest Artifacts
    ItemArchetype {
        id: ItemKindId::AmuletOfYendor,
        name: "Amulet of Yendor",
        class: ItemClass::Amulet,
        weight: 20,
        cost: 30000,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::AmuletOfReflection,
        name: "amulet of reflection",
        class: ItemClass::Amulet,
        weight: 20,
        cost: 150,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    // Signature Artifacts
    ItemArchetype {
        id: ItemKindId::Excalibur,
        name: "Excalibur",
        class: ItemClass::Weapon,
        weight: 30,
        cost: 4000,
        damage_small: (1, 8),
        damage_large: (1, 12),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::VorpalBlade,
        name: "Vorpal Blade",
        class: ItemClass::Weapon,
        weight: 30,
        cost: 4000,
        damage_small: (1, 8),
        damage_large: (1, 12),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::Mjollnir,
        name: "Mjollnir",
        class: ItemClass::Weapon,
        weight: 50,
        cost: 4000,
        damage_small: (1, 4),
        damage_large: (1, 4),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::Magicbane,
        name: "Magicbane",
        class: ItemClass::Weapon,
        weight: 10,
        cost: 3500,
        damage_small: (1, 4),
        damage_large: (1, 3),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::EyeOfTheAethiopica,
        name: "The Eye of the Aethiopica",
        class: ItemClass::Amulet,
        weight: 20,
        cost: 4000,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    // Gold & Gems
    ItemArchetype {
        id: ItemKindId::GoldPieces,
        name: "gold pieces",
        class: ItemClass::Coin,
        weight: 1,
        cost: 1,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::Luckstone,
        name: "luckstone",
        class: ItemClass::Gem,
        weight: 10,
        cost: 60,
        damage_small: (0, 0),
        damage_large: (0, 0),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    // Invocation Artifacts
    ItemArchetype {
        id: ItemKindId::BellOfOpening,
        name: "Bell of Opening",
        class: ItemClass::Tool,
        weight: 10,
        cost: 5000,
        damage_small: (1, 4),
        damage_large: (1, 4),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::CandelabrumOfInvocation,
        name: "Candelabrum of Invocation",
        class: ItemClass::Tool,
        weight: 20,
        cost: 5000,
        damage_small: (1, 4),
        damage_large: (1, 4),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::BookOfTheDead,
        name: "Book of the Dead",
        class: ItemClass::Spellbook,
        weight: 20,
        cost: 10000,
        damage_small: (1, 4),
        damage_large: (1, 4),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::WaxCandle,
        name: "wax candle",
        class: ItemClass::Tool,
        weight: 2,
        cost: 10,
        damage_small: (1, 2),
        damage_large: (1, 2),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::OrbOfFate,
        name: "The Orb of Fate",
        class: ItemClass::Tool,
        weight: 30,
        cost: 3500,
        damage_small: (1, 6),
        damage_large: (1, 6),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::HeartOfAhriman,
        name: "The Heart of Ahriman",
        class: ItemClass::Gem,
        weight: 10,
        cost: 2500,
        damage_small: (1, 4),
        damage_large: (1, 4),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::MagicMirrorOfMerlin,
        name: "The Magic Mirror of Merlin",
        class: ItemClass::Tool,
        weight: 15,
        cost: 1500,
        damage_small: (1, 4),
        damage_large: (1, 4),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::EyesOfTheOverworld,
        name: "The Eyes of the Overworld",
        class: ItemClass::Tool,
        weight: 10,
        cost: 2500,
        damage_small: (1, 2),
        damage_large: (1, 2),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::MasterKeyOfThievery,
        name: "The Master Key of Thievery",
        class: ItemClass::Tool,
        weight: 10,
        cost: 3500,
        damage_small: (1, 6),
        damage_large: (1, 6),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::TsurugiOfMuramasa,
        name: "The Tsurugi of Muramasa",
        class: ItemClass::Weapon,
        weight: 60,
        cost: 4500,
        damage_small: (2, 8),
        damage_large: (3, 8),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::PlatinumYendorianExpressCard,
        name: "The Platinum Yendorian Express Card",
        class: ItemClass::Tool,
        weight: 5,
        cost: 7000,
        damage_small: (1, 2),
        damage_large: (1, 2),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::StaffOfAesculapius,
        name: "The Staff of Aesculapius",
        class: ItemClass::Weapon,
        weight: 30,
        cost: 5000,
        damage_small: (2, 6),
        damage_large: (2, 6),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
    ItemArchetype {
        id: ItemKindId::OrbOfDetection,
        name: "The Orb of Detection",
        class: ItemClass::Tool,
        weight: 30,
        cost: 2500,
        damage_small: (1, 4),
        damage_large: (1, 4),
        ac_bonus: 0,
        is_container: false,
        is_bag_of_holding: false,
    },
];

/// Look up an item archetype from the catalog table.
pub fn get_item_archetype(id: ItemKindId) -> &'static ItemArchetype {
    ITEM_CATALOG
        .iter()
        .find(|item| item.id == id)
        .expect("All ItemKindId variants must have a catalog entry")
}

use netrust_types::Buc;

/// Factory function to spawn an ItemRecord from declarative archetype data.
pub fn create_item_record(id: ItemKindId, location: ItemLocation, buc: Buc) -> ItemRecord {
    let arch = get_item_archetype(id);
    ItemRecord {
        name: arch.name.to_string(),
        class: arch.class,
        weight: arch.weight,
        buc,
        is_container: arch.is_container,
        is_bag_of_holding: arch.is_bag_of_holding,
        enchantment: 0,
        erosion: 0,
        proofed: false,
        location,
    }
}
