//! Declarative monster bestiary and species registry for NetRust.

use netrust_arena::ActorRecord;
use netrust_types::{Alignment, Coord, GazeType, Intrinsics, MonsterAbility, MonsterSpell};
use serde::{Deserialize, Serialize};

/// Re-exported from `netrust-types` so `netrust-core` combat can take an [`Attack`].
pub use netrust_types::{Attack, AttackType, DamageType};

/// Enumeration of canonical monster species.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum MonsterSpeciesId {
    Goblin,
    Hobgoblin,
    Orc,
    Kobold,
    Jackal,
    GiantAnt,
    FloatingEye,
    Skeleton,
    Vampire,
    SilverDragon,
    RedDragon,
    Medusa,
    Lich,
    Shopkeeper,
    LittleDog,
    Dog,
    LargeDog,
    Kitten,
    Housecat,
    LargeCat,
    Ghost,
    Djinni,
    Gnome,
    Dwarf,
    Priest,
    Watchman,
    // Quest Leaders
    TheNorn,
    NeferetTheGreen,
    Pelias,
    KingArthur,
    GrandMaster,
    MasterAssassin,
    Hippocrates,
    Twoflower,
    LordCarnarvon,
    // Quest Nemeses
    LordSurtur,
    TheDarkOne,
    ThothAmon,
    Ixoth,
    MasterKaen,
    MasterOfThieves,
    Cyclops,
    MinionOfHuhetotl,
    // Quest Guardians (role.c guardnum)
    Student,
    Chieftain,
    Attendant,
    Page,
    Abbot,
    Thug,
    Guide,
    Warrior,
    Apprentice,
    // Bosses
    WizardOfYendor,
    VladTheImpaler,
    Croesus,
}

/// Behavioral archetype for autonomous monster decision making.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AiBehavior {
    /// Actively computes Dijkstra gradient to hunt and attack player.
    MeleeHunter,
    /// Pursues player, but reverses gradient to flee when HP < 30% or when facing Elbereth.
    CautiousHunter,
    /// Passive watcher, attacks only when provoked.
    Stationary,
    /// Peaceful shopkeeper defending store merchandise.
    Shopkeeper,
    /// Loyal pet following hero, displacing when stepped on, attacking hostiles.
    CompanionPet,
}

/// C monster size (`MZ_*`, include/monflag.h:174-180).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum MonsterSize {
    Tiny,
    Small,
    Medium,
    Large,
    Huge,
    Gigantic,
}

/// Declarative specification of a monster species.
#[derive(Debug, Clone, Serialize)]
pub struct MonsterArchetype {
    pub id: MonsterSpeciesId,
    pub name: &'static str,
    pub glyph: char,
    pub base_hp: u32,
    pub max_hp: u32,
    pub ac: i32,
    pub level: u32,
    pub speed: u32,
    pub alignment: Alignment,
    pub intrinsics: Intrinsics,
    /// C `mattk[]` (up to 6 attacks; only trailing NO_ATTK slots are omitted, so
    /// the slice index is the C slot `i` of the `rnd(20 + i)` to-hit die). The sim
    /// resolves melee from it (`netrust-sim` combat) and breath from its AT_BREA.
    pub attacks: &'static [Attack],
    /// C `msize` (`MZ_*`; `MZ_HUMAN` is `MZ_MEDIUM`).
    pub size: MonsterSize,
    /// C `M2_PEACEFUL` (monst.c flags; always peaceful before alignment checks).
    pub peaceful_by_default: bool,
    /// C `M2_HUMAN`.
    pub is_human: bool,
    /// C `G_UNIQ`.
    pub is_unique: bool,
    /// C `M1_MINDLESS`.
    pub mindless: bool,
    pub ai_behavior: AiBehavior,
    /// Sim tactical abilities. Gaze and spellcasting only act when `attacks`
    /// has the matching AT_GAZE / AT_MAGC entry (Medusa's gaze; lich, Dark One,
    /// Thoth Amon and Wizard of Yendor spells). Breath is driven by AT_BREA.
    pub abilities: &'static [MonsterAbility],
}

pub static BESTIARY: &[MonsterArchetype] = &[
    MonsterArchetype {
        id: MonsterSpeciesId::Goblin,
        name: "goblin",
        glyph: 'o',
        base_hp: 8,
        max_hp: 8,
        ac: 10,
        level: 0,
        speed: 6,
        alignment: Alignment::Chaotic,
        intrinsics: Intrinsics::empty(),
        attacks: &[Attack {
            at: AttackType::Weapon,
            ad: DamageType::Phys,
            n: 1,
            d: 4,
        }],
        size: MonsterSize::Small,
        peaceful_by_default: false,
        is_human: false,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::CautiousHunter,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Hobgoblin,
        name: "hobgoblin",
        glyph: 'o',
        base_hp: 12,
        max_hp: 12,
        ac: 10,
        level: 1,
        speed: 9,
        alignment: Alignment::Chaotic,
        intrinsics: Intrinsics::empty(),
        attacks: &[Attack {
            at: AttackType::Weapon,
            ad: DamageType::Phys,
            n: 1,
            d: 6,
        }],
        size: MonsterSize::Medium,
        peaceful_by_default: false,
        is_human: false,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::CautiousHunter,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Orc,
        name: "hill orc",
        glyph: 'o',
        base_hp: 14,
        max_hp: 14,
        ac: 10,
        level: 2,
        speed: 9,
        alignment: Alignment::Chaotic,
        intrinsics: Intrinsics {
            poison_resistance: true,
            ..Intrinsics::empty()
        },
        attacks: &[Attack {
            at: AttackType::Weapon,
            ad: DamageType::Phys,
            n: 1,
            d: 6,
        }],
        size: MonsterSize::Medium,
        peaceful_by_default: false,
        is_human: false,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Kobold,
        name: "kobold",
        glyph: 'k',
        base_hp: 6,
        max_hp: 6,
        ac: 10,
        level: 0,
        speed: 6,
        alignment: Alignment::Chaotic,
        intrinsics: Intrinsics {
            poison_resistance: true,
            ..Intrinsics::empty()
        },
        attacks: &[Attack {
            at: AttackType::Weapon,
            ad: DamageType::Phys,
            n: 1,
            d: 4,
        }],
        size: MonsterSize::Small,
        peaceful_by_default: false,
        is_human: false,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::CautiousHunter,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Jackal,
        name: "jackal",
        glyph: 'd',
        base_hp: 5,
        max_hp: 5,
        ac: 7,
        level: 0,
        speed: 12,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics::empty(),
        attacks: &[Attack {
            at: AttackType::Bite,
            ad: DamageType::Phys,
            n: 1,
            d: 2,
        }],
        size: MonsterSize::Small,
        peaceful_by_default: false,
        is_human: false,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::GiantAnt,
        name: "giant ant",
        glyph: 'a',
        base_hp: 16,
        max_hp: 16,
        ac: 3,
        level: 2,
        speed: 18,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics::empty(),
        attacks: &[Attack {
            at: AttackType::Bite,
            ad: DamageType::Phys,
            n: 1,
            d: 4,
        }],
        size: MonsterSize::Tiny,
        peaceful_by_default: false,
        is_human: false,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::FloatingEye,
        name: "floating eye",
        glyph: 'e',
        base_hp: 10,
        max_hp: 10,
        ac: 9,
        level: 2,
        speed: 1,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics::empty(),
        attacks: &[Attack {
            at: AttackType::Passive,
            ad: DamageType::Paralyze,
            n: 0,
            d: 70,
        }],
        size: MonsterSize::Small,
        peaceful_by_default: false,
        is_human: false,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::Stationary,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Skeleton,
        name: "skeleton",
        glyph: 'Z',
        base_hp: 18,
        max_hp: 18,
        ac: 4,
        level: 12,
        speed: 8,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics {
            cold_resistance: true,
            poison_resistance: true,
            sleep_resistance: true,
            ..Intrinsics::empty()
        },
        attacks: &[
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 2,
                d: 6,
            },
            Attack {
                at: AttackType::Touch,
                ad: DamageType::Slow,
                n: 1,
                d: 6,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: false,
        is_human: false,
        is_unique: false,
        mindless: true,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Vampire,
        name: "vampire",
        glyph: 'V',
        base_hp: 45,
        max_hp: 45,
        ac: 1,
        level: 10,
        speed: 12,
        alignment: Alignment::Chaotic,
        intrinsics: Intrinsics {
            poison_resistance: true,
            sleep_resistance: true,
            ..Intrinsics::empty()
        },
        attacks: &[
            Attack {
                at: AttackType::Claw,
                ad: DamageType::Phys,
                n: 1,
                d: 6,
            },
            Attack {
                at: AttackType::Bite,
                ad: DamageType::DrainLife,
                n: 1,
                d: 6,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: false,
        is_human: false,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::SilverDragon,
        name: "silver dragon",
        glyph: 'D',
        base_hp: 90,
        max_hp: 90,
        ac: -1,
        level: 15,
        speed: 9,
        alignment: Alignment::Lawful,
        intrinsics: Intrinsics {
            cold_resistance: true,
            reflection: true,
            see_invisible: true,
            ..Intrinsics::empty()
        },
        attacks: &[
            Attack {
                at: AttackType::Breath,
                ad: DamageType::Cold,
                n: 4,
                d: 6,
            },
            Attack {
                at: AttackType::Bite,
                ad: DamageType::Phys,
                n: 3,
                d: 8,
            },
            Attack {
                at: AttackType::Claw,
                ad: DamageType::Phys,
                n: 1,
                d: 4,
            },
            Attack {
                at: AttackType::Claw,
                ad: DamageType::Phys,
                n: 1,
                d: 4,
            },
        ],
        size: MonsterSize::Gigantic,
        peaceful_by_default: false,
        is_human: false,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::RedDragon,
        name: "red dragon",
        glyph: 'D',
        base_hp: 90,
        max_hp: 90,
        ac: -1,
        level: 15,
        speed: 9,
        alignment: Alignment::Chaotic,
        intrinsics: Intrinsics {
            fire_resistance: true,
            see_invisible: true,
            ..Intrinsics::empty()
        },
        attacks: &[
            Attack {
                at: AttackType::Breath,
                ad: DamageType::Fire,
                n: 6,
                d: 6,
            },
            Attack {
                at: AttackType::Bite,
                ad: DamageType::Phys,
                n: 3,
                d: 8,
            },
            Attack {
                at: AttackType::Claw,
                ad: DamageType::Phys,
                n: 1,
                d: 4,
            },
            Attack {
                at: AttackType::Claw,
                ad: DamageType::Phys,
                n: 1,
                d: 4,
            },
        ],
        size: MonsterSize::Gigantic,
        peaceful_by_default: false,
        is_human: false,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Medusa,
        name: "medusa",
        glyph: '@',
        base_hp: 75,
        max_hp: 75,
        ac: 2,
        level: 20,
        speed: 12,
        alignment: Alignment::Chaotic,
        intrinsics: Intrinsics {
            poison_resistance: true,
            ..Intrinsics::empty()
        },
        attacks: &[
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 2,
                d: 4,
            },
            Attack {
                at: AttackType::Claw,
                ad: DamageType::Phys,
                n: 1,
                d: 8,
            },
            Attack {
                at: AttackType::Gaze,
                ad: DamageType::Stone,
                n: 0,
                d: 0,
            },
            Attack {
                at: AttackType::Bite,
                ad: DamageType::DrainStr,
                n: 1,
                d: 6,
            },
        ],
        size: MonsterSize::Large,
        peaceful_by_default: false,
        is_human: false,
        is_unique: true,
        mindless: false,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[MonsterAbility::Gaze {
            gaze: GazeType::Petrification,
        }],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Lich,
        name: "master lich",
        glyph: 'L',
        base_hp: 80,
        max_hp: 80,
        ac: -4,
        level: 17,
        speed: 9,
        alignment: Alignment::Chaotic,
        intrinsics: Intrinsics {
            cold_resistance: true,
            fire_resistance: true,
            poison_resistance: true,
            sleep_resistance: true,
            ..Intrinsics::empty()
        },
        attacks: &[
            Attack {
                at: AttackType::Touch,
                ad: DamageType::Cold,
                n: 3,
                d: 6,
            },
            Attack {
                at: AttackType::Magic,
                ad: DamageType::Spell,
                n: 0,
                d: 0,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: false,
        is_human: false,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[MonsterAbility::Spellcaster {
            spell: MonsterSpell::SummonMonsters,
            cooldown_turns: 8,
        }],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Shopkeeper,
        name: "shopkeeper",
        glyph: '@',
        base_hp: 60,
        max_hp: 60,
        ac: 0,
        level: 12,
        speed: 16,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics {
            magic_resistance: true,
            ..Intrinsics::empty()
        },
        attacks: &[
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 4,
                d: 4,
            },
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 4,
                d: 4,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: true,
        is_human: true,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::Shopkeeper,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::LittleDog,
        name: "little dog",
        glyph: 'd',
        base_hp: 12,
        max_hp: 12,
        ac: 6,
        level: 2,
        speed: 18,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics::empty(),
        attacks: &[Attack {
            at: AttackType::Bite,
            ad: DamageType::Phys,
            n: 1,
            d: 6,
        }],
        size: MonsterSize::Small,
        peaceful_by_default: false,
        is_human: false,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::CompanionPet,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Dog,
        name: "dog",
        glyph: 'd',
        base_hp: 24,
        max_hp: 24,
        ac: 5,
        level: 4,
        speed: 16,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics::empty(),
        attacks: &[Attack {
            at: AttackType::Bite,
            ad: DamageType::Phys,
            n: 1,
            d: 6,
        }],
        size: MonsterSize::Medium,
        peaceful_by_default: false,
        is_human: false,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::CompanionPet,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::LargeDog,
        name: "large dog",
        glyph: 'd',
        base_hp: 45,
        max_hp: 45,
        ac: 4,
        level: 6,
        speed: 15,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics::empty(),
        attacks: &[Attack {
            at: AttackType::Bite,
            ad: DamageType::Phys,
            n: 2,
            d: 4,
        }],
        size: MonsterSize::Medium,
        peaceful_by_default: false,
        is_human: false,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::CompanionPet,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Kitten,
        name: "kitten",
        glyph: 'f',
        base_hp: 10,
        max_hp: 10,
        ac: 6,
        level: 2,
        speed: 18,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics::empty(),
        attacks: &[Attack {
            at: AttackType::Bite,
            ad: DamageType::Phys,
            n: 1,
            d: 6,
        }],
        size: MonsterSize::Small,
        peaceful_by_default: false,
        is_human: false,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::CompanionPet,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Housecat,
        name: "housecat",
        glyph: 'f',
        base_hp: 20,
        max_hp: 20,
        ac: 5,
        level: 4,
        speed: 16,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics::empty(),
        attacks: &[Attack {
            at: AttackType::Bite,
            ad: DamageType::Phys,
            n: 1,
            d: 6,
        }],
        size: MonsterSize::Small,
        peaceful_by_default: false,
        is_human: false,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::CompanionPet,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::LargeCat,
        name: "large cat",
        glyph: 'f',
        base_hp: 40,
        max_hp: 40,
        ac: 4,
        level: 6,
        speed: 15,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics::empty(),
        attacks: &[Attack {
            at: AttackType::Bite,
            ad: DamageType::Phys,
            n: 2,
            d: 4,
        }],
        size: MonsterSize::Small,
        peaceful_by_default: false,
        is_human: false,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::CompanionPet,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Ghost,
        name: "ghost",
        glyph: ' ',
        base_hp: 20,
        max_hp: 20,
        ac: -5,
        level: 10,
        speed: 3,
        alignment: Alignment::Chaotic,
        intrinsics: Intrinsics {
            cold_resistance: true,
            disintegration_resistance: true,
            poison_resistance: true,
            sleep_resistance: true,
            ..Intrinsics::empty()
        },
        attacks: &[Attack {
            at: AttackType::Touch,
            ad: DamageType::Phys,
            n: 1,
            d: 1,
        }],
        size: MonsterSize::Medium,
        peaceful_by_default: false,
        is_human: false,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Djinni,
        name: "djinni",
        glyph: '&',
        base_hp: 55,
        max_hp: 55,
        ac: 4,
        level: 7,
        speed: 12,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics {
            poison_resistance: true,
            ..Intrinsics::empty()
        },
        attacks: &[Attack {
            at: AttackType::Weapon,
            ad: DamageType::Phys,
            n: 2,
            d: 8,
        }],
        size: MonsterSize::Medium,
        peaceful_by_default: false,
        is_human: false,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Gnome,
        name: "gnome",
        glyph: 'G',
        base_hp: 8,
        max_hp: 8,
        ac: 10,
        level: 1,
        speed: 6,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics::empty(),
        attacks: &[Attack {
            at: AttackType::Weapon,
            ad: DamageType::Phys,
            n: 1,
            d: 6,
        }],
        size: MonsterSize::Small,
        peaceful_by_default: false,
        is_human: false,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Dwarf,
        name: "dwarf",
        glyph: 'h',
        base_hp: 16,
        max_hp: 16,
        ac: 10,
        level: 2,
        speed: 6,
        alignment: Alignment::Lawful,
        intrinsics: Intrinsics::empty(),
        attacks: &[Attack {
            at: AttackType::Weapon,
            ad: DamageType::Phys,
            n: 1,
            d: 8,
        }],
        size: MonsterSize::Medium,
        peaceful_by_default: false,
        is_human: false,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Priest,
        name: "priest",
        glyph: '@',
        base_hp: 60,
        max_hp: 60,
        ac: 10,
        level: 12,
        speed: 12,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics {
            shock_resistance: true,
            ..Intrinsics::empty()
        },
        attacks: &[
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 4,
                d: 10,
            },
            Attack {
                at: AttackType::Kick,
                ad: DamageType::Phys,
                n: 1,
                d: 4,
            },
            Attack {
                at: AttackType::Magic,
                ad: DamageType::Clerical,
                n: 0,
                d: 0,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: true,
        is_human: true,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::Stationary,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Watchman,
        name: "watchman",
        glyph: '@',
        base_hp: 28,
        max_hp: 28,
        ac: 10,
        level: 6,
        speed: 10,
        alignment: Alignment::Chaotic,
        intrinsics: Intrinsics::empty(),
        attacks: &[Attack {
            at: AttackType::Weapon,
            ad: DamageType::Phys,
            n: 1,
            d: 8,
        }],
        size: MonsterSize::Medium,
        peaceful_by_default: true,
        is_human: true,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::Stationary,
        abilities: &[],
    },
    // Quest Leaders (peaceful by default)
    MonsterArchetype {
        id: MonsterSpeciesId::TheNorn,
        name: "The Norn",
        glyph: '@',
        base_hp: 200,
        max_hp: 200,
        ac: 0,
        level: 20,
        speed: 15,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics {
            cold_resistance: true,
            ..Intrinsics::empty()
        },
        attacks: &[
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 4,
                d: 10,
            },
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 4,
                d: 10,
            },
        ],
        size: MonsterSize::Huge,
        peaceful_by_default: true,
        is_human: true,
        is_unique: true,
        mindless: false,
        ai_behavior: AiBehavior::Stationary,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::NeferetTheGreen,
        name: "Neferet the Green",
        glyph: '@',
        base_hp: 220,
        max_hp: 220,
        ac: 0,
        level: 20,
        speed: 15,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics::empty(),
        attacks: &[
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 4,
                d: 10,
            },
            Attack {
                at: AttackType::Magic,
                ad: DamageType::Spell,
                n: 2,
                d: 8,
            },
            Attack {
                at: AttackType::Magic,
                ad: DamageType::Spell,
                n: 2,
                d: 8,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: true,
        is_human: true,
        is_unique: true,
        mindless: false,
        ai_behavior: AiBehavior::Stationary,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Pelias,
        name: "Pelias",
        glyph: '@',
        base_hp: 250,
        max_hp: 250,
        ac: 0,
        level: 20,
        speed: 15,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics {
            poison_resistance: true,
            ..Intrinsics::empty()
        },
        attacks: &[
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 4,
                d: 10,
            },
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 4,
                d: 10,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: true,
        is_human: true,
        is_unique: true,
        mindless: false,
        ai_behavior: AiBehavior::Stationary,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::KingArthur,
        name: "King Arthur",
        glyph: '@',
        base_hp: 240,
        max_hp: 240,
        ac: 0,
        level: 20,
        speed: 15,
        alignment: Alignment::Lawful,
        intrinsics: Intrinsics::empty(),
        attacks: &[
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 4,
                d: 10,
            },
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 4,
                d: 10,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: true,
        is_human: true,
        is_unique: true,
        mindless: false,
        ai_behavior: AiBehavior::Stationary,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::GrandMaster,
        name: "Grand Master",
        glyph: '@',
        base_hp: 210,
        max_hp: 210,
        ac: 0,
        level: 25,
        speed: 15,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics {
            fire_resistance: true,
            poison_resistance: true,
            see_invisible: true,
            shock_resistance: true,
            sleep_resistance: true,
            ..Intrinsics::empty()
        },
        attacks: &[
            Attack {
                at: AttackType::Claw,
                ad: DamageType::Phys,
                n: 4,
                d: 10,
            },
            Attack {
                at: AttackType::Kick,
                ad: DamageType::Phys,
                n: 2,
                d: 8,
            },
            Attack {
                at: AttackType::Magic,
                ad: DamageType::Clerical,
                n: 2,
                d: 8,
            },
            Attack {
                at: AttackType::Magic,
                ad: DamageType::Clerical,
                n: 2,
                d: 8,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: true,
        is_human: true,
        is_unique: true,
        mindless: false,
        ai_behavior: AiBehavior::Stationary,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::MasterAssassin,
        name: "Master Assassin",
        glyph: '@',
        base_hp: 190,
        max_hp: 190,
        ac: 0,
        level: 15,
        speed: 12,
        alignment: Alignment::Lawful,
        intrinsics: Intrinsics::empty(),
        attacks: &[
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::DrainStr,
                n: 2,
                d: 6,
            },
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 2,
                d: 8,
            },
            Attack {
                at: AttackType::Claw,
                ad: DamageType::StealAmulet,
                n: 2,
                d: 6,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: false,
        is_human: true,
        is_unique: true,
        mindless: false,
        ai_behavior: AiBehavior::Stationary,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Hippocrates,
        name: "Hippocrates",
        glyph: '@',
        base_hp: 180,
        max_hp: 180,
        ac: 0,
        level: 20,
        speed: 15,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics {
            poison_resistance: true,
            ..Intrinsics::empty()
        },
        attacks: &[
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 1,
                d: 6,
            },
            Attack {
                at: AttackType::Magic,
                ad: DamageType::Clerical,
                n: 3,
                d: 8,
            },
            Attack {
                at: AttackType::Magic,
                ad: DamageType::Clerical,
                n: 3,
                d: 8,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: true,
        is_human: true,
        is_unique: true,
        mindless: false,
        ai_behavior: AiBehavior::Stationary,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Twoflower,
        name: "Twoflower",
        glyph: '@',
        base_hp: 150,
        max_hp: 150,
        ac: 10,
        level: 20,
        speed: 15,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics::empty(),
        attacks: &[Attack {
            at: AttackType::Weapon,
            ad: DamageType::Phys,
            n: 4,
            d: 10,
        }],
        size: MonsterSize::Medium,
        peaceful_by_default: true,
        is_human: true,
        is_unique: true,
        mindless: false,
        ai_behavior: AiBehavior::Stationary,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::LordCarnarvon,
        name: "Lord Carnarvon",
        glyph: '@',
        base_hp: 200,
        max_hp: 200,
        ac: 0,
        level: 20,
        speed: 15,
        alignment: Alignment::Lawful,
        intrinsics: Intrinsics::empty(),
        attacks: &[
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 4,
                d: 10,
            },
            Attack {
                at: AttackType::Magic,
                ad: DamageType::Spell,
                n: 4,
                d: 8,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: true,
        is_human: true,
        is_unique: true,
        mindless: false,
        ai_behavior: AiBehavior::Stationary,
        abilities: &[],
    },
    // Quest Nemeses (hostile guardians of the quest artifacts)
    MonsterArchetype {
        id: MonsterSpeciesId::LordSurtur,
        name: "Lord Surtur",
        glyph: 'H',
        base_hp: 280,
        max_hp: 280,
        ac: 2,
        level: 15,
        speed: 12,
        alignment: Alignment::Lawful,
        intrinsics: Intrinsics {
            fire_resistance: true,
            ..Intrinsics::empty()
        },
        attacks: &[
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 2,
                d: 10,
            },
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 2,
                d: 10,
            },
            Attack {
                at: AttackType::Claw,
                ad: DamageType::StealAmulet,
                n: 2,
                d: 6,
            },
        ],
        size: MonsterSize::Huge,
        peaceful_by_default: false,
        is_human: false,
        is_unique: true,
        mindless: false,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::TheDarkOne,
        name: "The Dark One",
        glyph: '@',
        base_hp: 260,
        max_hp: 260,
        ac: 0,
        level: 15,
        speed: 12,
        alignment: Alignment::Chaotic,
        intrinsics: Intrinsics::empty(),
        attacks: &[
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 1,
                d: 6,
            },
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 1,
                d: 6,
            },
            Attack {
                at: AttackType::Claw,
                ad: DamageType::StealAmulet,
                n: 1,
                d: 4,
            },
            Attack {
                at: AttackType::Magic,
                ad: DamageType::Spell,
                n: 0,
                d: 0,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: false,
        is_human: true,
        is_unique: true,
        mindless: false,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[
            MonsterAbility::Spellcaster {
                spell: MonsterSpell::CurseItems,
                cooldown_turns: 6,
            },
            MonsterAbility::Spellcaster {
                spell: MonsterSpell::SummonMonsters,
                cooldown_turns: 8,
            },
        ],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::ThothAmon,
        name: "Thoth Amon",
        glyph: '@',
        base_hp: 270,
        max_hp: 270,
        ac: 0,
        level: 16,
        speed: 12,
        alignment: Alignment::Chaotic,
        intrinsics: Intrinsics {
            poison_resistance: true,
            ..Intrinsics::empty()
        },
        attacks: &[
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 1,
                d: 6,
            },
            Attack {
                at: AttackType::Magic,
                ad: DamageType::Spell,
                n: 0,
                d: 0,
            },
            Attack {
                at: AttackType::Magic,
                ad: DamageType::Spell,
                n: 0,
                d: 0,
            },
            Attack {
                at: AttackType::Claw,
                ad: DamageType::StealAmulet,
                n: 1,
                d: 4,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: false,
        is_human: true,
        is_unique: true,
        mindless: false,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[MonsterAbility::Spellcaster {
            spell: MonsterSpell::SummonMonsters,
            cooldown_turns: 8,
        }],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Ixoth,
        name: "Ixoth",
        glyph: 'D',
        base_hp: 300,
        max_hp: 300,
        ac: -1,
        level: 15,
        speed: 12,
        alignment: Alignment::Chaotic,
        intrinsics: Intrinsics {
            fire_resistance: true,
            see_invisible: true,
            ..Intrinsics::empty()
        },
        attacks: &[
            Attack {
                at: AttackType::Breath,
                ad: DamageType::Fire,
                n: 8,
                d: 6,
            },
            Attack {
                at: AttackType::Bite,
                ad: DamageType::Phys,
                n: 4,
                d: 8,
            },
            Attack {
                at: AttackType::Magic,
                ad: DamageType::Spell,
                n: 0,
                d: 0,
            },
            Attack {
                at: AttackType::Claw,
                ad: DamageType::Phys,
                n: 2,
                d: 4,
            },
            Attack {
                at: AttackType::Claw,
                ad: DamageType::StealAmulet,
                n: 2,
                d: 4,
            },
        ],
        size: MonsterSize::Gigantic,
        peaceful_by_default: false,
        is_human: false,
        is_unique: true,
        mindless: false,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::MasterKaen,
        name: "Master Kaen",
        glyph: '@',
        base_hp: 290,
        max_hp: 290,
        ac: -10,
        level: 25,
        speed: 12,
        alignment: Alignment::Chaotic,
        intrinsics: Intrinsics {
            poison_resistance: true,
            see_invisible: true,
            ..Intrinsics::empty()
        },
        attacks: &[
            Attack {
                at: AttackType::Claw,
                ad: DamageType::Phys,
                n: 16,
                d: 2,
            },
            Attack {
                at: AttackType::Claw,
                ad: DamageType::Phys,
                n: 16,
                d: 2,
            },
            Attack {
                at: AttackType::Magic,
                ad: DamageType::Clerical,
                n: 0,
                d: 0,
            },
            Attack {
                at: AttackType::Claw,
                ad: DamageType::StealAmulet,
                n: 1,
                d: 4,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: false,
        is_human: true,
        is_unique: true,
        mindless: false,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::MasterOfThieves,
        name: "Master of Thieves",
        glyph: '@',
        base_hp: 240,
        max_hp: 240,
        ac: 0,
        level: 20,
        speed: 15,
        alignment: Alignment::Chaotic,
        intrinsics: Intrinsics::empty(),
        attacks: &[
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 4,
                d: 10,
            },
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 2,
                d: 6,
            },
            Attack {
                at: AttackType::Claw,
                ad: DamageType::StealAmulet,
                n: 2,
                d: 4,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: true,
        is_human: true,
        is_unique: true,
        mindless: false,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Cyclops,
        name: "Cyclops",
        glyph: 'H',
        base_hp: 250,
        max_hp: 250,
        ac: 0,
        level: 18,
        speed: 12,
        alignment: Alignment::Chaotic,
        intrinsics: Intrinsics::empty(),
        attacks: &[
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 4,
                d: 8,
            },
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 4,
                d: 8,
            },
            Attack {
                at: AttackType::Claw,
                ad: DamageType::StealAmulet,
                n: 2,
                d: 6,
            },
        ],
        size: MonsterSize::Huge,
        peaceful_by_default: false,
        is_human: false,
        is_unique: true,
        mindless: false,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::MinionOfHuhetotl,
        name: "Minion of Huhetotl",
        glyph: '&',
        base_hp: 270,
        max_hp: 270,
        ac: -2,
        level: 16,
        speed: 12,
        alignment: Alignment::Chaotic,
        intrinsics: Intrinsics {
            fire_resistance: true,
            poison_resistance: true,
            see_invisible: true,
            ..Intrinsics::empty()
        },
        attacks: &[
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 8,
                d: 4,
            },
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 4,
                d: 6,
            },
            Attack {
                at: AttackType::Magic,
                ad: DamageType::Spell,
                n: 0,
                d: 0,
            },
            Attack {
                at: AttackType::Claw,
                ad: DamageType::StealAmulet,
                n: 2,
                d: 6,
            },
        ],
        size: MonsterSize::Large,
        peaceful_by_default: false,
        is_human: false,
        is_unique: true,
        mindless: false,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[],
    },
    // Quest Guardians (C monsters.h:3773-3914 LVL(5, 12, ac, mr, align); role.c guardnum :48-:550). HP: mean of 5d8.
    MonsterArchetype {
        id: MonsterSpeciesId::Student,
        name: "student",
        glyph: '@',
        base_hp: 22,
        max_hp: 22,
        ac: 10,
        level: 5,
        speed: 12,
        alignment: Alignment::Lawful,
        intrinsics: Intrinsics::empty(),
        attacks: &[Attack {
            at: AttackType::Weapon,
            ad: DamageType::Phys,
            n: 1,
            d: 6,
        }],
        size: MonsterSize::Medium,
        peaceful_by_default: true,
        is_human: true,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::Stationary,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Chieftain,
        name: "chieftain",
        glyph: '@',
        base_hp: 22,
        max_hp: 22,
        ac: 10,
        level: 5,
        speed: 12,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics {
            poison_resistance: true,
            ..Intrinsics::empty()
        },
        attacks: &[Attack {
            at: AttackType::Weapon,
            ad: DamageType::Phys,
            n: 1,
            d: 6,
        }],
        size: MonsterSize::Medium,
        peaceful_by_default: true,
        is_human: true,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::Stationary,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Attendant,
        name: "attendant",
        glyph: '@',
        base_hp: 22,
        max_hp: 22,
        ac: 10,
        level: 5,
        speed: 12,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics {
            poison_resistance: true,
            ..Intrinsics::empty()
        },
        attacks: &[Attack {
            at: AttackType::Weapon,
            ad: DamageType::Phys,
            n: 1,
            d: 6,
        }],
        size: MonsterSize::Medium,
        peaceful_by_default: true,
        is_human: true,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::Stationary,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Page,
        name: "page",
        glyph: '@',
        base_hp: 22,
        max_hp: 22,
        ac: 10,
        level: 5,
        speed: 12,
        alignment: Alignment::Lawful,
        intrinsics: Intrinsics::empty(),
        attacks: &[
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 1,
                d: 6,
            },
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 1,
                d: 6,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: true,
        is_human: true,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::Stationary,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Abbot,
        name: "abbot",
        glyph: '@',
        base_hp: 22,
        max_hp: 22,
        ac: 10,
        level: 5,
        speed: 12,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics::empty(),
        attacks: &[
            Attack {
                at: AttackType::Claw,
                ad: DamageType::Phys,
                n: 8,
                d: 2,
            },
            Attack {
                at: AttackType::Kick,
                ad: DamageType::Stun,
                n: 3,
                d: 2,
            },
            Attack {
                at: AttackType::Magic,
                ad: DamageType::Clerical,
                n: 0,
                d: 0,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: true,
        is_human: true,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::Stationary,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Thug,
        name: "thug",
        glyph: '@',
        base_hp: 22,
        max_hp: 22,
        ac: 10,
        level: 5,
        speed: 12,
        alignment: Alignment::Chaotic,
        intrinsics: Intrinsics::empty(),
        attacks: &[
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 1,
                d: 6,
            },
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 1,
                d: 6,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: true,
        is_human: true,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::Stationary,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Guide,
        name: "guide",
        glyph: '@',
        base_hp: 22,
        max_hp: 22,
        ac: 10,
        level: 5,
        speed: 12,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics::empty(),
        attacks: &[
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 1,
                d: 6,
            },
            Attack {
                at: AttackType::Magic,
                ad: DamageType::Spell,
                n: 0,
                d: 0,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: true,
        is_human: true,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::Stationary,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Warrior,
        name: "warrior",
        glyph: '@',
        base_hp: 22,
        max_hp: 22,
        ac: 10,
        level: 5,
        speed: 12,
        alignment: Alignment::Lawful,
        intrinsics: Intrinsics::empty(),
        attacks: &[
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 1,
                d: 8,
            },
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 1,
                d: 8,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: true,
        is_human: true,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::Stationary,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Apprentice,
        name: "apprentice",
        glyph: '@',
        base_hp: 22,
        max_hp: 22,
        ac: 10,
        level: 5,
        speed: 12,
        alignment: Alignment::Neutral,
        intrinsics: Intrinsics::empty(),
        attacks: &[
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 1,
                d: 6,
            },
            Attack {
                at: AttackType::Magic,
                ad: DamageType::Spell,
                n: 0,
                d: 0,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: true,
        is_human: true,
        is_unique: false,
        mindless: false,
        ai_behavior: AiBehavior::Stationary,
        abilities: &[],
    },
    // Bosses
    MonsterArchetype {
        id: MonsterSpeciesId::WizardOfYendor,
        name: "Wizard of Yendor",
        glyph: '@',
        base_hp: 300,
        max_hp: 300,
        ac: -8,
        level: 30,
        speed: 12,
        alignment: Alignment::Unaligned,
        intrinsics: Intrinsics {
            fire_resistance: true,
            poison_resistance: true,
            see_invisible: true,
            ..Intrinsics::empty()
        },
        attacks: &[
            Attack {
                at: AttackType::Claw,
                ad: DamageType::StealAmulet,
                n: 2,
                d: 12,
            },
            Attack {
                at: AttackType::Magic,
                ad: DamageType::Spell,
                n: 0,
                d: 0,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: false,
        is_human: true,
        is_unique: true,
        mindless: false,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[MonsterAbility::Spellcaster {
            spell: MonsterSpell::SummonMonsters,
            cooldown_turns: 5,
        }],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::VladTheImpaler,
        name: "Vlad the Impaler",
        glyph: 'V',
        base_hp: 250,
        max_hp: 250,
        ac: -6,
        level: 28,
        speed: 26,
        alignment: Alignment::Chaotic,
        intrinsics: Intrinsics {
            poison_resistance: true,
            sleep_resistance: true,
            ..Intrinsics::empty()
        },
        attacks: &[
            Attack {
                at: AttackType::Weapon,
                ad: DamageType::Phys,
                n: 2,
                d: 10,
            },
            Attack {
                at: AttackType::Bite,
                ad: DamageType::DrainLife,
                n: 1,
                d: 12,
            },
        ],
        size: MonsterSize::Medium,
        peaceful_by_default: false,
        is_human: false,
        is_unique: true,
        mindless: false,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[],
    },
    MonsterArchetype {
        id: MonsterSpeciesId::Croesus,
        name: "Croesus",
        glyph: '@',
        base_hp: 280,
        max_hp: 280,
        ac: 0,
        level: 20,
        speed: 15,
        alignment: Alignment::Lawful,
        intrinsics: Intrinsics {
            see_invisible: true,
            ..Intrinsics::empty()
        },
        attacks: &[Attack {
            at: AttackType::Weapon,
            ad: DamageType::Phys,
            n: 4,
            d: 10,
        }],
        size: MonsterSize::Medium,
        peaceful_by_default: false,
        is_human: true,
        is_unique: true,
        mindless: false,
        ai_behavior: AiBehavior::MeleeHunter,
        abilities: &[],
    },
];

/// NetHack monster class letter (bestiary glyph) for a species name, case-insensitive.
pub fn monster_class_of(name: &str) -> Option<char> {
    BESTIARY
        .iter()
        .find(|m| m.name.eq_ignore_ascii_case(name))
        .map(|m| m.glyph)
}

/// Find a bestiary entry by display name, case-insensitively.
///
/// Strips the sim's runtime name decorations first: a leading `"hostile "`
/// (pacified/angered monsters, e.g. `"hostile djinni"`) and a leading
/// `"ghost of "` (bones ghosts, resolving to the `ghost` species).
pub fn monster_archetype_by_name(name: &str) -> Option<&'static MonsterArchetype> {
    let lower = name.to_ascii_lowercase();
    let base = if lower.starts_with("ghost of ") {
        "ghost"
    } else {
        lower.strip_prefix("hostile ").unwrap_or(&lower)
    };
    BESTIARY.iter().find(|m| m.name.eq_ignore_ascii_case(base))
}

/// Look up a monster archetype from the bestiary table.
pub fn get_monster_species(id: MonsterSpeciesId) -> &'static MonsterArchetype {
    BESTIARY
        .iter()
        .find(|m| m.id == id)
        .expect("All MonsterSpeciesId variants must have a bestiary entry")
}

/// Factory function to spawn an ActorRecord from declarative archetype data.
pub fn create_monster_record(id: MonsterSpeciesId, coord: Coord) -> ActorRecord {
    let arch = get_monster_species(id);
    ActorRecord {
        name: arch.name.to_string(),
        coord,
        hp: arch.base_hp,
        max_hp: arch.max_hp,
        ac: arch.ac,
        level: arch.level,
        speed: arch.speed,
        alignment: arch.alignment,
        intrinsics: arch.intrinsics,
        is_player: false,
        is_unique: arch.is_unique,
        is_dead: false,
        is_tame: arch.ai_behavior == AiBehavior::CompanionPet,
        tameness: if arch.ai_behavior == AiBehavior::CompanionPet {
            5
        } else {
            0
        },
        abilities: arch.abilities.to_vec(),
        is_peaceful: arch.peaceful_by_default,
    }
}

/// Spawns a hostile ghost representing a deceased adventurer from a graveyard bones file.
pub fn create_ghost_record(name: &str, level: u32, hp: u32, coord: Coord) -> ActorRecord {
    let mut rec = create_monster_record(MonsterSpeciesId::Ghost, coord);
    rec.name = format!("ghost of {name}");
    rec.level = level;
    rec.max_hp = hp;
    rec.hp = hp;
    rec
}
