//! Table test: every BESTIARY entry against values extracted from NetHack C
//! `include/monsters.h` (LVL(), ATTK(), SIZ(), MR_*, M1_/M2_/G_ flags).
//! Rows: (species id debug name, class glyph, level, speed, AC, alignment,
//! size, attacks (AT, AD, n, d), resistance/see-invis intrinsics,
//! peaceful_by_default, is_human, is_unique, mindless).
//! Includes the nine per-role quest guardians (role.c `guardnum`).
//!
//! NOTE: the expected table was generated from `NetHack-5.0.0/include/monsters.h`
//! by the same script that generated the data (not an independent check).
//! `monsters.h` is git-ignored, so CI cannot parse it; this test pins the
//! generated values against accidental edits. `magic_resistance`, `reflection`
//! and the names are pinned in the small tables below (they are NetRust
//! modelling choices, not columns of the C-derived table).
//! HP is rolled in C (`d(lvl,8)`) and is not compared here.

use netrust_data::monsters::{get_monster_species, monster_archetype_by_name, MonsterSpeciesId};
use netrust_data::BESTIARY;

type Row = (
    &'static str,
    char,
    u32,
    u32,
    i32,
    &'static str,
    &'static str,
    &'static [(&'static str, &'static str, u8, u8)],
    &'static [&'static str],
    bool,
    bool,
    bool,
    bool,
);

const C_TABLE: &[Row] = &[
    (
        "Goblin",
        'o',
        0,
        6,
        10,
        "Chaotic",
        "Small",
        &[("Weapon", "Phys", 1, 4)],
        &[],
        false,
        false,
        false,
        false,
    ),
    (
        "Hobgoblin",
        'o',
        1,
        9,
        10,
        "Chaotic",
        "Medium",
        &[("Weapon", "Phys", 1, 6)],
        &[],
        false,
        false,
        false,
        false,
    ),
    (
        "Orc",
        'o',
        2,
        9,
        10,
        "Chaotic",
        "Medium",
        &[("Weapon", "Phys", 1, 6)],
        &["poison_resistance"],
        false,
        false,
        false,
        false,
    ),
    (
        "Kobold",
        'k',
        0,
        6,
        10,
        "Chaotic",
        "Small",
        &[("Weapon", "Phys", 1, 4)],
        &["poison_resistance"],
        false,
        false,
        false,
        false,
    ),
    (
        "Jackal",
        'd',
        0,
        12,
        7,
        "Neutral",
        "Small",
        &[("Bite", "Phys", 1, 2)],
        &[],
        false,
        false,
        false,
        false,
    ),
    (
        "GiantAnt",
        'a',
        2,
        18,
        3,
        "Neutral",
        "Tiny",
        &[("Bite", "Phys", 1, 4)],
        &[],
        false,
        false,
        false,
        false,
    ),
    (
        "FloatingEye",
        'e',
        2,
        1,
        9,
        "Neutral",
        "Small",
        &[("Passive", "Paralyze", 0, 70)],
        &[],
        false,
        false,
        false,
        false,
    ),
    (
        "Skeleton",
        'Z',
        12,
        8,
        4,
        "Neutral",
        "Medium",
        &[("Weapon", "Phys", 2, 6), ("Touch", "Slow", 1, 6)],
        &["cold_resistance", "poison_resistance", "sleep_resistance"],
        false,
        false,
        false,
        true,
    ),
    (
        "Vampire",
        'V',
        10,
        12,
        1,
        "Chaotic",
        "Medium",
        &[("Claw", "Phys", 1, 6), ("Bite", "DrainLife", 1, 6)],
        &["poison_resistance", "sleep_resistance"],
        false,
        false,
        false,
        false,
    ),
    (
        "SilverDragon",
        'D',
        15,
        9,
        -1,
        "Lawful",
        "Gigantic",
        &[
            ("Breath", "Cold", 4, 6),
            ("Bite", "Phys", 3, 8),
            ("Claw", "Phys", 1, 4),
            ("Claw", "Phys", 1, 4),
        ],
        &["cold_resistance", "see_invisible"],
        false,
        false,
        false,
        false,
    ),
    (
        "RedDragon",
        'D',
        15,
        9,
        -1,
        "Chaotic",
        "Gigantic",
        &[
            ("Breath", "Fire", 6, 6),
            ("Bite", "Phys", 3, 8),
            ("Claw", "Phys", 1, 4),
            ("Claw", "Phys", 1, 4),
        ],
        &["fire_resistance", "see_invisible"],
        false,
        false,
        false,
        false,
    ),
    (
        "Medusa",
        '@',
        20,
        12,
        2,
        "Chaotic",
        "Large",
        &[
            ("Weapon", "Phys", 2, 4),
            ("Claw", "Phys", 1, 8),
            ("Gaze", "Stone", 0, 0),
            ("Bite", "DrainStr", 1, 6),
        ],
        &["poison_resistance"],
        false,
        false,
        true,
        false,
    ),
    (
        "Lich",
        'L',
        17,
        9,
        -4,
        "Chaotic",
        "Medium",
        &[("Touch", "Cold", 3, 6), ("Magic", "Spell", 0, 0)],
        &[
            "cold_resistance",
            "fire_resistance",
            "poison_resistance",
            "sleep_resistance",
        ],
        false,
        false,
        false,
        false,
    ),
    (
        "Shopkeeper",
        '@',
        12,
        16,
        0,
        "Neutral",
        "Medium",
        &[("Weapon", "Phys", 4, 4), ("Weapon", "Phys", 4, 4)],
        &[],
        true,
        true,
        false,
        false,
    ),
    (
        "LittleDog",
        'd',
        2,
        18,
        6,
        "Neutral",
        "Small",
        &[("Bite", "Phys", 1, 6)],
        &[],
        false,
        false,
        false,
        false,
    ),
    (
        "Dog",
        'd',
        4,
        16,
        5,
        "Neutral",
        "Medium",
        &[("Bite", "Phys", 1, 6)],
        &[],
        false,
        false,
        false,
        false,
    ),
    (
        "LargeDog",
        'd',
        6,
        15,
        4,
        "Neutral",
        "Medium",
        &[("Bite", "Phys", 2, 4)],
        &[],
        false,
        false,
        false,
        false,
    ),
    (
        "Kitten",
        'f',
        2,
        18,
        6,
        "Neutral",
        "Small",
        &[("Bite", "Phys", 1, 6)],
        &[],
        false,
        false,
        false,
        false,
    ),
    (
        "Housecat",
        'f',
        4,
        16,
        5,
        "Neutral",
        "Small",
        &[("Bite", "Phys", 1, 6)],
        &[],
        false,
        false,
        false,
        false,
    ),
    (
        "LargeCat",
        'f',
        6,
        15,
        4,
        "Neutral",
        "Small",
        &[("Bite", "Phys", 2, 4)],
        &[],
        false,
        false,
        false,
        false,
    ),
    (
        "Ghost",
        ' ',
        10,
        3,
        -5,
        "Chaotic",
        "Medium",
        &[("Touch", "Phys", 1, 1)],
        &[
            "cold_resistance",
            "disintegration_resistance",
            "poison_resistance",
            "sleep_resistance",
        ],
        false,
        false,
        false,
        false,
    ),
    (
        "Djinni",
        '&',
        7,
        12,
        4,
        "Neutral",
        "Medium",
        &[("Weapon", "Phys", 2, 8)],
        &["poison_resistance"],
        false,
        false,
        false,
        false,
    ),
    (
        "Gnome",
        'G',
        1,
        6,
        10,
        "Neutral",
        "Small",
        &[("Weapon", "Phys", 1, 6)],
        &[],
        false,
        false,
        false,
        false,
    ),
    (
        "Dwarf",
        'h',
        2,
        6,
        10,
        "Lawful",
        "Medium",
        &[("Weapon", "Phys", 1, 8)],
        &[],
        false,
        false,
        false,
        false,
    ),
    (
        "Priest",
        '@',
        12,
        12,
        10,
        "Neutral",
        "Medium",
        &[
            ("Weapon", "Phys", 4, 10),
            ("Kick", "Phys", 1, 4),
            ("Magic", "Clerical", 0, 0),
        ],
        &["shock_resistance"],
        true,
        true,
        false,
        false,
    ),
    (
        "Watchman",
        '@',
        6,
        10,
        10,
        "Chaotic",
        "Medium",
        &[("Weapon", "Phys", 1, 8)],
        &[],
        true,
        true,
        false,
        false,
    ),
    (
        "TheNorn",
        '@',
        20,
        15,
        0,
        "Neutral",
        "Huge",
        &[("Weapon", "Phys", 4, 10), ("Weapon", "Phys", 4, 10)],
        &["cold_resistance"],
        true,
        true,
        true,
        false,
    ),
    (
        "NeferetTheGreen",
        '@',
        20,
        15,
        0,
        "Neutral",
        "Medium",
        &[
            ("Weapon", "Phys", 4, 10),
            ("Magic", "Spell", 2, 8),
            ("Magic", "Spell", 2, 8),
        ],
        &[],
        true,
        true,
        true,
        false,
    ),
    (
        "Pelias",
        '@',
        20,
        15,
        0,
        "Neutral",
        "Medium",
        &[("Weapon", "Phys", 4, 10), ("Weapon", "Phys", 4, 10)],
        &["poison_resistance"],
        true,
        true,
        true,
        false,
    ),
    (
        "KingArthur",
        '@',
        20,
        15,
        0,
        "Lawful",
        "Medium",
        &[("Weapon", "Phys", 4, 10), ("Weapon", "Phys", 4, 10)],
        &[],
        true,
        true,
        true,
        false,
    ),
    (
        "GrandMaster",
        '@',
        25,
        15,
        0,
        "Neutral",
        "Medium",
        &[
            ("Claw", "Phys", 4, 10),
            ("Kick", "Phys", 2, 8),
            ("Magic", "Clerical", 2, 8),
            ("Magic", "Clerical", 2, 8),
        ],
        &[
            "fire_resistance",
            "poison_resistance",
            "see_invisible",
            "shock_resistance",
            "sleep_resistance",
        ],
        true,
        true,
        true,
        false,
    ),
    (
        "MasterAssassin",
        '@',
        15,
        12,
        0,
        "Lawful",
        "Medium",
        &[
            ("Weapon", "DrainStr", 2, 6),
            ("Weapon", "Phys", 2, 8),
            ("Claw", "StealAmulet", 2, 6),
        ],
        &[],
        false,
        true,
        true,
        false,
    ),
    (
        "Hippocrates",
        '@',
        20,
        15,
        0,
        "Neutral",
        "Medium",
        &[
            ("Weapon", "Phys", 1, 6),
            ("Magic", "Clerical", 3, 8),
            ("Magic", "Clerical", 3, 8),
        ],
        &["poison_resistance"],
        true,
        true,
        true,
        false,
    ),
    (
        "Twoflower",
        '@',
        20,
        15,
        10,
        "Neutral",
        "Medium",
        &[("Weapon", "Phys", 4, 10)],
        &[],
        true,
        true,
        true,
        false,
    ),
    (
        "LordCarnarvon",
        '@',
        20,
        15,
        0,
        "Lawful",
        "Medium",
        &[("Weapon", "Phys", 4, 10), ("Magic", "Spell", 4, 8)],
        &[],
        true,
        true,
        true,
        false,
    ),
    (
        "LordSurtur",
        'H',
        15,
        12,
        2,
        "Lawful",
        "Huge",
        &[
            ("Weapon", "Phys", 2, 10),
            ("Weapon", "Phys", 2, 10),
            ("Claw", "StealAmulet", 2, 6),
        ],
        &["fire_resistance"],
        false,
        false,
        true,
        false,
    ),
    (
        "TheDarkOne",
        '@',
        15,
        12,
        0,
        "Chaotic",
        "Medium",
        &[
            ("Weapon", "Phys", 1, 6),
            ("Weapon", "Phys", 1, 6),
            ("Claw", "StealAmulet", 1, 4),
            ("Magic", "Spell", 0, 0),
        ],
        &[],
        false,
        true,
        true,
        false,
    ),
    (
        "ThothAmon",
        '@',
        16,
        12,
        0,
        "Chaotic",
        "Medium",
        &[
            ("Weapon", "Phys", 1, 6),
            ("Magic", "Spell", 0, 0),
            ("Magic", "Spell", 0, 0),
            ("Claw", "StealAmulet", 1, 4),
        ],
        &["poison_resistance"],
        false,
        true,
        true,
        false,
    ),
    (
        "Ixoth",
        'D',
        15,
        12,
        -1,
        "Chaotic",
        "Gigantic",
        &[
            ("Breath", "Fire", 8, 6),
            ("Bite", "Phys", 4, 8),
            ("Magic", "Spell", 0, 0),
            ("Claw", "Phys", 2, 4),
            ("Claw", "StealAmulet", 2, 4),
        ],
        &["fire_resistance", "see_invisible"],
        false,
        false,
        true,
        false,
    ),
    (
        "MasterKaen",
        '@',
        25,
        12,
        -10,
        "Chaotic",
        "Medium",
        &[
            ("Claw", "Phys", 16, 2),
            ("Claw", "Phys", 16, 2),
            ("Magic", "Clerical", 0, 0),
            ("Claw", "StealAmulet", 1, 4),
        ],
        &["poison_resistance", "see_invisible"],
        false,
        true,
        true,
        false,
    ),
    (
        "MasterOfThieves",
        '@',
        20,
        15,
        0,
        "Chaotic",
        "Medium",
        &[
            ("Weapon", "Phys", 4, 10),
            ("Weapon", "Phys", 2, 6),
            ("Claw", "StealAmulet", 2, 4),
        ],
        &[],
        true,
        true,
        true,
        false,
    ),
    (
        "Cyclops",
        'H',
        18,
        12,
        0,
        "Chaotic",
        "Huge",
        &[
            ("Weapon", "Phys", 4, 8),
            ("Weapon", "Phys", 4, 8),
            ("Claw", "StealAmulet", 2, 6),
        ],
        &[],
        false,
        false,
        true,
        false,
    ),
    (
        "MinionOfHuhetotl",
        '&',
        16,
        12,
        -2,
        "Chaotic",
        "Large",
        &[
            ("Weapon", "Phys", 8, 4),
            ("Weapon", "Phys", 4, 6),
            ("Magic", "Spell", 0, 0),
            ("Claw", "StealAmulet", 2, 6),
        ],
        &["fire_resistance", "poison_resistance", "see_invisible"],
        false,
        false,
        true,
        false,
    ),
    (
        "WizardOfYendor",
        '@',
        30,
        12,
        -8,
        "Unaligned",
        "Medium",
        &[("Claw", "StealAmulet", 2, 12), ("Magic", "Spell", 0, 0)],
        &["fire_resistance", "poison_resistance", "see_invisible"],
        false,
        true,
        true,
        false,
    ),
    (
        "VladTheImpaler",
        'V',
        28,
        26,
        -6,
        "Chaotic",
        "Medium",
        &[("Weapon", "Phys", 2, 10), ("Bite", "DrainLife", 1, 12)],
        &["poison_resistance", "sleep_resistance"],
        false,
        false,
        true,
        false,
    ),
    (
        "Croesus",
        '@',
        20,
        15,
        0,
        "Lawful",
        "Medium",
        &[("Weapon", "Phys", 4, 10)],
        &["see_invisible"],
        false,
        true,
        true,
        false,
    ),
    (
        "Student",
        '@',
        5,
        12,
        10,
        "Lawful",
        "Medium",
        &[("Weapon", "Phys", 1, 6)],
        &[],
        true,
        true,
        false,
        false,
    ),
    (
        "Chieftain",
        '@',
        5,
        12,
        10,
        "Neutral",
        "Medium",
        &[("Weapon", "Phys", 1, 6)],
        &["poison_resistance"],
        true,
        true,
        false,
        false,
    ),
    (
        "Attendant",
        '@',
        5,
        12,
        10,
        "Neutral",
        "Medium",
        &[("Weapon", "Phys", 1, 6)],
        &["poison_resistance"],
        true,
        true,
        false,
        false,
    ),
    (
        "Page",
        '@',
        5,
        12,
        10,
        "Lawful",
        "Medium",
        &[("Weapon", "Phys", 1, 6), ("Weapon", "Phys", 1, 6)],
        &[],
        true,
        true,
        false,
        false,
    ),
    (
        "Abbot",
        '@',
        5,
        12,
        20,
        "Neutral",
        "Medium",
        &[
            ("Claw", "Phys", 8, 2),
            ("Kick", "Stun", 3, 2),
            ("Magic", "Clerical", 0, 0),
        ],
        &[],
        true,
        true,
        false,
        false,
    ),
    (
        "Thug",
        '@',
        5,
        12,
        10,
        "Chaotic",
        "Medium",
        &[("Weapon", "Phys", 1, 6), ("Weapon", "Phys", 1, 6)],
        &[],
        true,
        true,
        false,
        false,
    ),
    (
        "Guide",
        '@',
        5,
        12,
        20,
        "Neutral",
        "Medium",
        &[("Weapon", "Phys", 1, 6), ("Magic", "Spell", 0, 0)],
        &[],
        true,
        true,
        false,
        false,
    ),
    (
        "Warrior",
        '@',
        5,
        12,
        10,
        "Lawful",
        "Medium",
        &[("Weapon", "Phys", 1, 8), ("Weapon", "Phys", 1, 8)],
        &[],
        true,
        true,
        false,
        false,
    ),
    (
        "Apprentice",
        '@',
        5,
        12,
        30,
        "Neutral",
        "Medium",
        &[("Weapon", "Phys", 1, 6), ("Magic", "Spell", 0, 0)],
        &[],
        true,
        true,
        false,
        false,
    ),
];

fn intrinsic_flags(i: &netrust_types::Intrinsics) -> Vec<&'static str> {
    let mut v = Vec::new();
    for (on, n) in [
        (i.fire_resistance, "fire_resistance"),
        (i.cold_resistance, "cold_resistance"),
        (i.shock_resistance, "shock_resistance"),
        (i.sleep_resistance, "sleep_resistance"),
        (i.poison_resistance, "poison_resistance"),
        (i.acid_resistance, "acid_resistance"),
        (i.disintegration_resistance, "disintegration_resistance"),
        (i.see_invisible, "see_invisible"),
    ] {
        if on {
            v.push(n);
        }
    }
    v
}

#[test]
fn bestiary_matches_c_table() {
    let mut seen = 0;
    for row in C_TABLE {
        let (id, glyph, lvl, spd, ac, aln, size, atks, res, peaceful, human, uniq, mindless) = *row;
        let arch = BESTIARY
            .iter()
            .find(|a| format!("{:?}", a.id) == id)
            .unwrap_or_else(|| panic!("missing species {id}"));
        seen += 1;
        assert_eq!(arch.glyph, glyph, "{id} glyph");
        assert_eq!(arch.level, lvl, "{id} level");
        assert_eq!(arch.speed, spd, "{id} speed");
        assert_eq!(arch.ac, ac, "{id} ac");
        assert_eq!(format!("{:?}", arch.alignment), aln, "{id} alignment");
        assert_eq!(format!("{:?}", arch.size), size, "{id} size");
        let got: Vec<(String, String, u8, u8)> = arch
            .attacks
            .iter()
            .map(|a| (format!("{:?}", a.at), format!("{:?}", a.ad), a.n, a.d))
            .collect();
        let want: Vec<(String, String, u8, u8)> = atks
            .iter()
            .map(|(a, b, n, d)| (a.to_string(), b.to_string(), *n, *d))
            .collect();
        assert_eq!(got, want, "{id} attacks");
        let mut gi = intrinsic_flags(&arch.intrinsics);
        // Modelled outside the C resistance mask: magic_resistance (MR %), reflection.
        gi.sort_unstable();
        assert_eq!(gi, res.to_vec(), "{id} intrinsics");
        assert_eq!(arch.peaceful_by_default, peaceful, "{id} peaceful");
        assert_eq!(arch.is_human, human, "{id} human");
        assert_eq!(arch.is_unique, uniq, "{id} unique");
        assert_eq!(arch.mindless, mindless, "{id} mindless");
    }
    // Every entry is covered.
    assert_eq!(seen, BESTIARY.len());
}

#[test]
fn lookup_by_name_strips_prefixes_and_ignores_case() {
    let ghost = monster_archetype_by_name("ghost of Conan").unwrap();
    assert_eq!(ghost.id, MonsterSpeciesId::Ghost);
    let djinni = monster_archetype_by_name("Hostile Djinni").unwrap();
    assert_eq!(djinni.id, MonsterSpeciesId::Djinni);
    assert_eq!(
        monster_archetype_by_name("LARGE DOG").unwrap().id,
        MonsterSpeciesId::LargeDog
    );
    assert!(monster_archetype_by_name("war dog").is_none());
    assert!(monster_archetype_by_name("no such thing").is_none());
    assert_eq!(get_monster_species(MonsterSpeciesId::Medusa).name, "medusa");
    assert!(get_monster_species(MonsterSpeciesId::Medusa).is_unique);
}

const NAMES: &[(&str, &str)] = &[
    ("Goblin", "goblin"),
    ("Hobgoblin", "hobgoblin"),
    ("Orc", "hill orc"),
    ("Kobold", "kobold"),
    ("Jackal", "jackal"),
    ("GiantAnt", "giant ant"),
    ("FloatingEye", "floating eye"),
    ("Skeleton", "skeleton"),
    ("Vampire", "vampire"),
    ("SilverDragon", "silver dragon"),
    ("RedDragon", "red dragon"),
    ("Medusa", "medusa"),
    ("Lich", "master lich"),
    ("Shopkeeper", "shopkeeper"),
    ("LittleDog", "little dog"),
    ("Dog", "dog"),
    ("LargeDog", "large dog"),
    ("Kitten", "kitten"),
    ("Housecat", "housecat"),
    ("LargeCat", "large cat"),
    ("Ghost", "ghost"),
    ("Djinni", "djinni"),
    ("Gnome", "gnome"),
    ("Dwarf", "dwarf"),
    ("Priest", "priest"),
    ("Watchman", "watchman"),
    ("TheNorn", "The Norn"),
    ("NeferetTheGreen", "Neferet the Green"),
    ("Pelias", "Pelias"),
    ("KingArthur", "King Arthur"),
    ("GrandMaster", "Grand Master"),
    ("MasterAssassin", "Master Assassin"),
    ("Hippocrates", "Hippocrates"),
    ("Twoflower", "Twoflower"),
    ("LordCarnarvon", "Lord Carnarvon"),
    ("LordSurtur", "Lord Surtur"),
    ("TheDarkOne", "The Dark One"),
    ("ThothAmon", "Thoth Amon"),
    ("Ixoth", "Ixoth"),
    ("MasterKaen", "Master Kaen"),
    ("MasterOfThieves", "Master of Thieves"),
    ("Cyclops", "Cyclops"),
    ("MinionOfHuhetotl", "Minion of Huhetotl"),
    ("Student", "student"),
    ("Chieftain", "chieftain"),
    ("Attendant", "attendant"),
    ("Page", "page"),
    ("Abbot", "abbot"),
    ("Thug", "thug"),
    ("Guide", "guide"),
    ("Warrior", "warrior"),
    ("Apprentice", "apprentice"),
    ("WizardOfYendor", "Wizard of Yendor"),
    ("VladTheImpaler", "Vlad the Impaler"),
    ("Croesus", "Croesus"),
];

#[test]
fn names_and_modelled_intrinsics_are_pinned() {
    assert_eq!(NAMES.len(), BESTIARY.len());
    for (id, name) in NAMES {
        let a = BESTIARY
            .iter()
            .find(|a| format!("{:?}", a.id) == *id)
            .unwrap_or_else(|| panic!("missing {id}"));
        assert_eq!(a.name, *name, "{id} name");
    }
    // magic_resistance / reflection are modelling choices: only these two entries set them.
    for a in BESTIARY {
        let id = format!("{:?}", a.id);
        assert_eq!(
            a.intrinsics.magic_resistance,
            id == "Shopkeeper",
            "{id} magic_resistance"
        );
        assert_eq!(
            a.intrinsics.reflection,
            id == "SilverDragon",
            "{id} reflection"
        );
    }
}
