//! Item catalog vs. a C-derived expected table (task D2-2).
//!
//! The expected table below is hand-transcribed from the vendored
//! `NetHack-5.0.0/include/objects.h` (WEAPON/ARMOR/POTION/SCROLL/SPELL/WAND/TOOL/FOOD
//! macros: cost, weight, small/large damage sides, `10 - a_ac`, `oc_magic`, `oc_dir`,
//! `oc_nutrition`) and `include/artilist.h` for artifacts (their base object's weight and
//! dice, artifact cost). Rows are
//! `(kind, cost, weight, dmg_small(n,sides), dmg_large(n,sides), ac, oc_magic, wand_dir, nutrition)`.
//! Known simplifications (documented in the formal-mechanics spec): corpse weight and
//! nutrition come from the monster in C, so the catalog keeps a placeholder weight of 50 and
//! nutrition 0; mace/Mjollnir `+1` small-target bonus and Tsurugi `+2d6` large bonus are not
//! representable as a single die and are omitted; wands carry nutrition 30 as in objects.h.

use netrust_data::items::WandDir;
use netrust_data::{get_item_archetype, ItemKindId, ITEM_CATALOG};

type Row = (
    ItemKindId,
    u32,
    u32,
    (u32, u32),
    (u32, u32),
    i32,
    bool,
    Option<WandDir>,
    u32,
);

const EXPECTED: &[Row] = &[
    (ItemKindId::Dagger, 4, 10, (1, 4), (1, 3), 0, false, None, 0),
    (
        ItemKindId::ShortSword,
        10,
        30,
        (1, 6),
        (1, 8),
        0,
        false,
        None,
        0,
    ),
    (
        ItemKindId::LongSword,
        15,
        40,
        (1, 8),
        (1, 12),
        0,
        false,
        None,
        0,
    ),
    (
        ItemKindId::SilverSaber,
        75,
        40,
        (1, 8),
        (1, 8),
        0,
        false,
        None,
        0,
    ),
    (ItemKindId::Mace, 5, 30, (1, 6), (1, 6), 0, false, None, 0),
    (
        ItemKindId::LeatherArmor,
        5,
        150,
        (0, 0),
        (0, 0),
        2,
        false,
        None,
        0,
    ),
    (
        ItemKindId::ChainMail,
        75,
        300,
        (0, 0),
        (0, 0),
        5,
        false,
        None,
        0,
    ),
    (
        ItemKindId::PlateMail,
        600,
        450,
        (0, 0),
        (0, 0),
        7,
        false,
        None,
        0,
    ),
    (
        ItemKindId::SilverDragonScaleMail,
        1200,
        40,
        (0, 0),
        (0, 0),
        9,
        true,
        None,
        0,
    ),
    (
        ItemKindId::CloakOfMagicResistance,
        60,
        10,
        (0, 0),
        (0, 0),
        1,
        true,
        None,
        0,
    ),
    (
        ItemKindId::WandOfStriking,
        150,
        7,
        (2, 12),
        (2, 12),
        0,
        true,
        Some(WandDir::Immediate),
        30,
    ),
    (
        ItemKindId::WandOfDigging,
        150,
        7,
        (0, 0),
        (0, 0),
        0,
        true,
        Some(WandDir::Ray),
        30,
    ),
    (
        ItemKindId::WandOfTeleportation,
        200,
        7,
        (0, 0),
        (0, 0),
        0,
        true,
        Some(WandDir::Immediate),
        30,
    ),
    (
        ItemKindId::WandOfDeath,
        500,
        7,
        (100, 1),
        (100, 1),
        0,
        true,
        Some(WandDir::Ray),
        30,
    ),
    (
        ItemKindId::WandOfWishing,
        500,
        7,
        (0, 0),
        (0, 0),
        0,
        true,
        Some(WandDir::NoDir),
        30,
    ),
    (
        ItemKindId::WandOfCold,
        175,
        7,
        (6, 6),
        (6, 6),
        0,
        true,
        Some(WandDir::Ray),
        30,
    ),
    (
        ItemKindId::WandOfSecretDoorDetection,
        150,
        7,
        (0, 0),
        (0, 0),
        0,
        true,
        Some(WandDir::NoDir),
        30,
    ),
    (
        ItemKindId::WandOfPolymorph,
        200,
        7,
        (0, 0),
        (0, 0),
        0,
        true,
        Some(WandDir::Immediate),
        30,
    ),
    (
        ItemKindId::PotionOfPolymorph,
        200,
        20,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::SprigOfWolfsbane,
        7,
        1,
        (0, 0),
        (0, 0),
        0,
        false,
        None,
        40,
    ),
    (
        ItemKindId::PotionOfHolyWater,
        100,
        20,
        (0, 0),
        (0, 0),
        0,
        false,
        None,
        0,
    ),
    (
        ItemKindId::PotionOfHealing,
        20,
        20,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::PotionOfExtraHealing,
        100,
        20,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::PotionOfSpeed,
        200,
        20,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::PotionOfWater,
        100,
        20,
        (0, 0),
        (0, 0),
        0,
        false,
        None,
        0,
    ),
    (
        ItemKindId::ScrollOfIdentify,
        20,
        5,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::ScrollOfTeleportation,
        100,
        5,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::ScrollOfRemoveCurse,
        80,
        5,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::ScrollOfEnchantWeapon,
        60,
        5,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::ScrollOfEnchantArmor,
        80,
        5,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::ScrollOfCharging,
        300,
        5,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::ScrollOfGenocide,
        300,
        5,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::MagicMarker,
        50,
        2,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (ItemKindId::Sack, 2, 15, (0, 0), (0, 0), 0, false, None, 0),
    (
        ItemKindId::BagOfHolding,
        100,
        15,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::Chest,
        16,
        600,
        (0, 0),
        (0, 0),
        0,
        false,
        None,
        0,
    ),
    (
        ItemKindId::MagicLamp,
        50,
        20,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::OilLamp,
        10,
        20,
        (0, 0),
        (0, 0),
        0,
        false,
        None,
        0,
    ),
    (
        ItemKindId::Boulder,
        0,
        6000,
        (1, 20),
        (1, 20),
        0,
        false,
        None,
        0,
    ),
    (
        ItemKindId::FoodRation,
        45,
        20,
        (0, 0),
        (0, 0),
        0,
        false,
        None,
        800,
    ),
    (ItemKindId::Apple, 7, 2, (0, 0), (0, 0), 0, false, None, 50),
    (ItemKindId::Corpse, 5, 50, (0, 0), (0, 0), 0, false, None, 0),
    (
        ItemKindId::SpellbookOfForceBolt,
        100,
        50,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::SpellbookOfHealing,
        100,
        50,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::AmuletOfYendor,
        30000,
        20,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::AmuletOfReflection,
        150,
        20,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::Excalibur,
        4000,
        40,
        (1, 8),
        (1, 12),
        0,
        false,
        None,
        0,
    ),
    (
        ItemKindId::VorpalBlade,
        4000,
        40,
        (1, 8),
        (1, 12),
        0,
        false,
        None,
        0,
    ),
    (
        ItemKindId::Mjollnir,
        4000,
        50,
        (1, 4),
        (1, 4),
        0,
        false,
        None,
        0,
    ),
    (
        ItemKindId::Magicbane,
        3500,
        10,
        (1, 4),
        (1, 3),
        0,
        false,
        None,
        0,
    ),
    (
        ItemKindId::EyeOfTheAethiopica,
        4000,
        20,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::OrbOfFate,
        3500,
        150,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::HeartOfAhriman,
        2500,
        10,
        (1, 3),
        (1, 3),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::MagicMirrorOfMerlin,
        1500,
        13,
        (0, 0),
        (0, 0),
        0,
        false,
        None,
        0,
    ),
    (
        ItemKindId::EyesOfTheOverworld,
        2500,
        3,
        (0, 0),
        (0, 0),
        0,
        false,
        None,
        0,
    ),
    (
        ItemKindId::MasterKeyOfThievery,
        3500,
        3,
        (0, 0),
        (0, 0),
        0,
        false,
        None,
        0,
    ),
    (
        ItemKindId::TsurugiOfMuramasa,
        4500,
        60,
        (1, 16),
        (1, 8),
        0,
        false,
        None,
        0,
    ),
    (
        ItemKindId::PlatinumYendorianExpressCard,
        7000,
        1,
        (0, 0),
        (0, 0),
        0,
        false,
        None,
        0,
    ),
    (
        ItemKindId::StaffOfAesculapius,
        5000,
        40,
        (1, 6),
        (1, 6),
        0,
        false,
        None,
        0,
    ),
    (
        ItemKindId::OrbOfDetection,
        2500,
        150,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::BellOfOpening,
        5000,
        10,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::CandelabrumOfInvocation,
        5000,
        10,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::BookOfTheDead,
        10000,
        50,
        (0, 0),
        (0, 0),
        0,
        true,
        None,
        0,
    ),
    (
        ItemKindId::WaxCandle,
        20,
        2,
        (0, 0),
        (0, 0),
        0,
        false,
        None,
        0,
    ),
    (
        ItemKindId::GoldPieces,
        1,
        1,
        (0, 0),
        (0, 0),
        0,
        false,
        None,
        0,
    ),
    (
        ItemKindId::Luckstone,
        60,
        10,
        (1, 3),
        (1, 3),
        0,
        true,
        None,
        0,
    ),
];

#[test]
fn catalog_matches_c_table() {
    assert_eq!(EXPECTED.len(), ITEM_CATALOG.len(), "every kind has a row");
    for &(id, cost, wt, ds, dl, ac, mgc, dir, nut) in EXPECTED {
        let a = get_item_archetype(id);
        assert_eq!(a.cost, cost, "{} cost", a.name);
        assert_eq!(a.weight, wt, "{} weight", a.name);
        assert_eq!(a.damage_small, ds, "{} damage_small", a.name);
        assert_eq!(a.damage_large, dl, "{} damage_large", a.name);
        assert_eq!(a.ac_bonus, ac, "{} ac", a.name);
        assert_eq!(a.oc_magic, mgc, "{} oc_magic", a.name);
        assert_eq!(a.wand_dir, dir, "{} wand_dir", a.name);
        assert_eq!(a.nutrition, nut, "{} nutrition", a.name);
    }
}

#[test]
fn every_wand_has_a_direction_and_nothing_else_does() {
    for a in ITEM_CATALOG {
        assert_eq!(
            a.wand_dir.is_some(),
            a.class == netrust_types::ItemClass::Wand,
            "{}",
            a.name
        );
    }
}

#[test]
fn new_fields_default_on_load() {
    // A record serialised before D2 lacks oc_magic / wand_dir / nutrition.
    let json = r#"{"id":"Dagger","name":"dagger","class":"Weapon","weight":10,"cost":4,
        "damage_small":[1,4],"damage_large":[1,3],"ac_bonus":0,
        "is_container":false,"is_bag_of_holding":false}"#;
    let a: netrust_data::ItemArchetype = serde_json::from_str(json).expect("loads");
    assert!(!a.oc_magic);
    assert_eq!(a.wand_dir, None);
    assert_eq!(a.nutrition, 0);
}

#[test]
fn lookup_by_name() {
    let a = netrust_data::item_archetype_by_name("wand of digging").unwrap();
    assert_eq!(a.id, ItemKindId::WandOfDigging);
    assert!(netrust_data::item_archetype_by_name("nonexistent").is_none());
}
