#!/usr/bin/env python3
"""Report which C data tags have engine behaviour (docs/parity/behaviour-coverage.md).

Data completeness is 100% by construction (scripts/extract/); behaviour is
Rust code. This lists every attack type, damage type and object kind with an
effect (wands, potions, scrolls, spellbooks, rings, amulets, tools) from
data/nethack-5.0/*.toml and checks whether engine code (nethacked-sim and
nethacked-core, excluding generated tables) names it: `AttackType::X`,
`DamageType::X`, `ItemKindId::ID`, or the object's name as a string literal.
A reference is evidence of handling, not proof of C fidelity; the parity
tables judge fidelity.

Usage: behaviour-coverage.py [--check]
"""
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts" / "extract"))
import gen_rust  # noqa: E402  (C vocabulary -> Rust variant maps)

OUT = ROOT / "docs" / "parity" / "behaviour-coverage.md"
ENGINE = [ROOT / "crates" / "nethacked-sim" / "src", ROOT / "crates" / "nethacked-core" / "src"]
EFFECT_CLASSES = ["wand", "potion", "scroll", "spbook", "ring", "amulet", "tool"]


def engine_text():
    parts = []
    for d in ENGINE:
        for p in sorted(d.rglob("*.rs")):
            if "generated" not in p.parts:
                parts.append(p.read_text())
    return "\n".join(parts)


def main():
    data = ROOT / "data" / "nethack-5.0"
    mons = tomllib.loads((data / "monsters.toml").read_text())["monster"]
    objs = tomllib.loads((data / "objects.toml").read_text())["object"]
    code = engine_text()
    lower = code.lower()

    def used_by(key):
        users = {}
        for m in mons:
            for a in m.get("attacks", []):
                users.setdefault(a[key], set()).add(m["name"])
        return users

    sections, summary = [], []
    for title, key, table, enum in [("Attack types (AT_*)", "at", gen_rust.AT, "AttackType"),
                                    ("Damage types (AD_*)", "ad", gen_rust.AD, "DamageType")]:
        users = used_by(key)
        rows, handled = [], 0
        for c, variant in sorted(table.items()):
            if c not in users:
                continue
            ok = re.search(rf"\b{enum}::{variant}\b", code) is not None
            handled += ok
            rows.append(f"| `{key.upper()}_{c.upper()}` | `{enum}::{variant}` | {len(users[c])} | "
                        f"{'✅' if ok else '❌'} |")
        summary.append((title, len(rows), handled))
        sections.append(f"## {title}\n\n| C | Rust | Species using it | Engine references it |\n"
                        f"|---|---|---|---|\n" + "\n".join(rows) + "\n")

    for cls in EFFECT_CLASSES:
        rows, handled = [], 0
        for o in objs:
            if o["class"] != cls or "name" not in o:
                continue
            name = gen_rust.object_name(o)
            ok = (re.search(rf"\bItemKindId::{o['id']}\b", code) is not None
                  or f'"{name.lower()}"' in lower)
            handled += ok
            rows.append(f"| `{o['id']}` | {name} | {'✅' if ok else '❌'} |")
        title = f"Objects: {gen_rust.CLASS[cls].lower()}s"
        summary.append((title, len(rows), handled))
        sections.append(f"## {title}\n\n| C id | Name | Engine references it |\n|---|---|---|\n"
                        + "\n".join(rows) + "\n")

    head = ["# Behaviour coverage", "",
            "GENERATED by `scripts/behaviour-coverage.py` (CI runs `--check`). Every row is C data that",
            "exists in NetHackED; ✅ means engine code (`nethacked-sim`, `nethacked-core`) names it, so some",
            "behaviour is attached. ❌ means the data exists but nothing acts on it yet. Fidelity to C is",
            "judged in the other parity tables.", "",
            "| Category | Total | Referenced | % |", "|---|---|---|---|"]
    head += [f"| {t} | {n} | {h} | {100 * h // n if n else 0}% |" for t, n, h in summary]
    text = "\n".join(head) + "\n\n" + "\n".join(sections)

    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            sys.exit("behaviour coverage stale (run scripts/behaviour-coverage.py)")
        print("behaviour coverage up to date")
    else:
        OUT.write_text(text)
        for t, n, h in summary:
            print(f"{t}: {h}/{n}")


if __name__ == "__main__":
    main()
