#!/usr/bin/env python3
"""Count feature statuses in the parity tables and keep docs/parity/README.md in sync.

Each table in docs/parity/<area>.md has a column whose header contains "Status";
its cells start with ✅ PRESENT, 🟡 PARTIAL, ❌ MISSING or ❔ UNSURE. Rows are
grouped by the nearest "## " heading or bold section row ("| **...** |").

  python3 scripts/parity-summary.py          # rewrite the summary block in README.md
  python3 scripts/parity-summary.py --check  # fail if README.md is out of date
"""

from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1] / "docs" / "parity"
AREAS = [
    ("flow-ui.md", "Game flow and interface"),
    ("hero.md", "The hero"),
    ("monsters-combat.md", "Monsters and combat"),
    ("objects-dungeon.md", "Objects and the dungeon"),
]
STATUSES = ["PRESENT", "PARTIAL", "MISSING", "UNSURE"]
ICON = {"PRESENT": "✅", "PARTIAL": "🟡", "MISSING": "❌", "UNSURE": "❔"}
BEGIN, END = "<!-- parity-summary:begin -->", "<!-- parity-summary:end -->"


def cells(line: str) -> list[str]:
    return [c.strip() for c in line.strip().strip("|").split("|")]


def count(path: Path) -> list[tuple[str, dict[str, int]]]:
    sections: list[tuple[str, dict[str, int]]] = []
    section = "General"
    status_col = None
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("## "):
            section = line[3:].strip()
            status_col = None
            continue
        if not line.startswith("|"):
            continue
        row = cells(line)
        if any("status" in c.lower() for c in row) and not any(
            s in " ".join(row) for s in STATUSES
        ):
            status_col = next(i for i, c in enumerate(row) if "status" in c.lower())
            continue
        if row and re.fullmatch(r"\*\*.+\*\*", row[0]) and all(not c for c in row[1:]):
            section = row[0].strip("*").strip()
            continue
        if status_col is None or status_col >= len(row):
            continue
        m = re.match(r"^\W*(PRESENT|PARTIAL|MISSING|UNSURE)\b", row[status_col])
        if not m:
            continue
        if not sections or sections[-1][0] != section:
            sections.append((section, {s: 0 for s in STATUSES}))
        sections[-1][1][m.group(1)] += 1
    return sections


def table_row(name: str, c: dict[str, int]) -> str:
    total = sum(c.values())
    done = 100 * c["PRESENT"] / total if total else 0
    return f"| {name} | {c['PRESENT']} | {c['PARTIAL']} | {c['MISSING']} | {c['UNSURE']} | {total} | {done:.0f}% |"


def render() -> str:
    head = "| Area | ✅ Present | 🟡 Partial | ❌ Missing | ❔ Unsure | Total | Present |\n|---|---:|---:|---:|---:|---:|---:|"
    overall = {s: 0 for s in STATUSES}
    area_rows, detail = [], []
    for file, title in AREAS:
        secs = count(ROOT / file)
        tot = {s: sum(c[s] for _, c in secs) for s in STATUSES}
        for s in STATUSES:
            overall[s] += tot[s]
        area_rows.append(table_row(f"[{title}]({file})", tot))
        detail.append(f"\n### {title}\n\n{head}\n" + "\n".join(table_row(n, c) for n, c in secs))
    out = [
        "Generated by `scripts/parity-summary.py` from the tables below; do not edit by hand.",
        "",
        head,
        *area_rows,
        table_row("**All areas**", overall),
        *detail,
    ]
    return "\n".join(out)


def main() -> None:
    readme = ROOT / "README.md"
    text = readme.read_text(encoding="utf-8")
    start, end = text.index(BEGIN) + len(BEGIN), text.index(END)
    new = text[:start] + "\n" + render() + "\n" + text[end:]
    if "--check" in sys.argv:
        if new != text:
            raise SystemExit("docs/parity/README.md summary is out of date; run scripts/parity-summary.py")
        print("parity summary up to date")
    else:
        readme.write_text(new, encoding="utf-8")
        print("updated", readme)


if __name__ == "__main__":
    main()
